# Generated by Django 2.2.2 on 2019-06-04 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('email', models.EmailField(max_length=256, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_staff', models.BooleanField(db_index=True, default=False, verbose_name='Is Staff')),
                ('is_superuser', models.BooleanField(db_index=True, default=False, verbose_name='Is Superuser')),
                ('birthday_notification', models.DateField(blank=True, null=True, verbose_name='Birthday Notification')),
                ('assessment_notification', models.DateField(blank=True, null=True, verbose_name='Assessment Notification')),
                ('full_name', models.CharField(blank=True, default='', max_length=256, verbose_name='Full Name')),
                ('ld_number', models.IntegerField(blank=True, null=True, verbose_name='L/D Number')),
                ('position', models.CharField(blank=True, max_length=68, null=True, verbose_name='Position')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('hired_date', models.DateField(blank=True, null=True, verbose_name='Hired Date')),
                ('end_of_contract', models.DateField(blank=True, null=True, verbose_name='End of Contract')),
                ('education', models.CharField(blank=True, max_length=32, null=True, verbose_name='Education')),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone Number')),
                ('phone_number2', models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone Number 2')),
                ('has_card', models.BooleanField(default=False, verbose_name='Has Card')),
                ('has_key', models.BooleanField(default=False, verbose_name='Has Key')),
                ('skype', models.CharField(blank=True, max_length=32, null=True, verbose_name='Skype')),
                ('working_hours', models.IntegerField(default=8, verbose_name='Working Hours')),
            ],
            options={
                'verbose_name_plural': 'Users',
                'ordering': ['-modified'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', max_length=32, verbose_name='Status')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('plan', models.TextField(blank=True, null=True, verbose_name='Plan')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('internal_notes', models.TextField(blank=True, null=True, verbose_name='Internal Notes')),
                ('decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_decision_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Assessments',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('reason', models.CharField(choices=[('vacation', 'Vacation'), ('illness', 'Illness'), ('holiday', 'Holiday'), ('other', 'Other')], default='other', max_length=32, verbose_name='Reason')),
                ('status', models.CharField(choices=[('new', 'New'), ('veryfing', 'Verifying'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='new', max_length=32, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_approved_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Absences',
                'ordering': ['-id'],
            },
        ),
    ]
