# Generated by Django 2.2.1 on 2019-06-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(through='skills.UserSkillModel', to='skills.Skill'),
        ),
    ]
