# Generated by Django 2.2.7 on 2019-11-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_key2',
            field=models.BooleanField(default=False, verbose_name='Has Key #2'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_key3',
            field=models.BooleanField(default=False, verbose_name='Has Key #3'),
        ),
    ]
