# Generated by Django 2.2.7 on 2019-11-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191121_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, choices=[('junior', 'Junior'), ('junior_plus', 'Junior+'), ('middle', 'Middle'), ('middle_plus', 'Middle+'), ('senior', 'Senior'), ('senior_plus', 'Senior+')], max_length=32, null=True, verbose_name='Level'),
        ),
    ]
