# Generated by Django 2.2.7 on 2019-11-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='colour',
            field=models.CharField(blank=True, choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red'), ('black', 'Black')], max_length=32, null=True, verbose_name='Colour'),
        ),
    ]
