version: '3.7'

networks:
  network:
    driver: bridge

volumes:
  ssm-data:
  redis-data:
  portainer-data:
  ssm-postgres-data:

services:
  web:
    image: "node:10.17.0"
    command: bash -c "npm install & npm run serve"
    restart: on-failure
    working_dir: /usr/src/frontend/
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/usr/src/frontend/
    depends_on:
      - ssm
    networks:
      - network

  ssm:
    build:
      context: ./
      dockerfile: ssm/docker/Dockerfile
      args:
         IMAGE: "${PYTHON_IMAGE}"
         APP_PATH: "/var/staff/ssm/"
         DATA_PATH: "/var/staff/data/"
         UID: "${UID}"
         GID: "${GID}"
    command:
      - bash
      - -c
      - |
        python3 manage.py collectstatic --no-input
        python3 manage.py migrate
        python3 manage.py create_admin
        python3 manage.py runserver 0.0.0.0:8000
    restart: on-failure
    env_file:
      - ssm/docker/env/local.env
    ports:
      - 8000:8000
    volumes:
      - ./ssm:/var/staff/ssm/
      - ssm-data:/var/ssm/data/
    depends_on:
      - postgres
      - redis
    networks:
      - network

  supervisor:
    build:
      context: ./
      dockerfile: ssm/docker/Dockerfile
      args:
          IMAGE: "${PYTHON_IMAGE}"
          APP_PATH: "/var/staff/ssm/"
          DATA_PATH: "/var/staff/data/"
          UID: "${UID}"
          GID: "${GID}"
    command: /usr/local/bin/supervisord -c /etc/supervisord.conf
    restart: on-failure
    env_file:
      - ssm/docker/env/local.env
    volumes:
      - ./ssm:/var/staff/ssm/
      - ssm-data:/var/ssm/data/
    depends_on:
      - postgres
      - redis
    networks:
      - network

  cron:
    build:
      context: ./
      dockerfile: ssm/docker/Dockerfile.cron
      args:
        IMAGE: "${PYTHON_IMAGE}"
        APP_PATH: "/var/staff/ssm/"
        CRON_PATH: "/etc/cron.d/"
        UID: "${UID}"
        GID: "${GID}"
    restart: on-failure
    env_file:
      - ssm/docker/env/local.env
    volumes:
      - ./ssm:/var/staff/ssm/
    networks:
      - network

  postgres:
    image: "postgres:11.5-alpine"
    env_file:
      - ssm/docker/env/local.env
    ports:
      - 8998:5432
    volumes:
      - ssm-postgres-data:/var/lib/postgresql/data
    networks:
      - network

  redis:
    image: "redis:5.0.6-alpine"
    volumes:
      - redis-data:/data
    networks:
      - network

  portainer:
    image: portainer/portainer:1.22.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    ports:
      - "9000:9000"
    networks:
      - network
