# Generated by Django 2.2.2 on 2019-06-04 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.CharField(max_length=256, verbose_name='Position')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('bonus', models.FloatField(blank=True, null=True, verbose_name='Bonus')),
                ('status', models.CharField(choices=[('new', 'New'), ('active', 'active'), ('closed', 'Closed'), ('failed', 'Failed')], default='new', max_length=32, verbose_name='Status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('recommended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vacancies',
                'ordering': ['bonus'],
            },
        ),
    ]
