# Generated by Django 2.2.2 on 2019-06-04 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ssm.projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('project_manager', 'Project manager'), ('developer', 'Developer'), ('tester', 'Tester'), ('business_analyst', 'Business Analyst'), ('frontend_developer', 'Front-end Developer'), ('backend_developer', 'Back-end Developer'), ('data_scientist', 'Data Scientist'), ('designer', 'Designer'), ('team_lead', 'Team Lead'), ('product_owner', 'Product Owner')], default='developer', max_length=64, verbose_name='Role')),
                ('hours_per_day', models.IntegerField(default=8, verbose_name='Hours Per Day')),
                ('joined_date', models.DateField(verbose_name='Joined Date')),
                ('left_date', models.DateField(blank=True, null=True, verbose_name='Left Date')),
            ],
            options={
                'verbose_name_plural': 'Members',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('specification', models.FileField(blank=True, null=True, upload_to=ssm.projects.models.directory_path, verbose_name='Specification')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('in progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='waiting', max_length=32, verbose_name='Status')),
                ('estimation_in_man_hours', models.IntegerField(blank=True, null=True, verbose_name='Estimation In Man-hours')),
                ('members', models.ManyToManyField(related_name='members', through='projects.MembersModel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ['-modified'],
            },
        ),
        migrations.AddField(
            model_name='membersmodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='membersmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='membersmodel',
            unique_together={('user', 'project', 'role')},
        ),
    ]
