# Generated by Django 2.2.7 on 2019-11-21 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('level', models.CharField(blank=True, max_length=128, null=True, verbose_name='Level')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=32, verbose_name='Priority')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='Requirements')),
                ('count', models.IntegerField(verbose_name='Count')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name_plural': 'Vacancies',
                'ordering': ['project'],
            },
        ),
    ]
