# Generated by Django 2.2.2 on 2019-06-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='google_calendar_email',
            field=models.CharField(default='', max_length=128, verbose_name='Google calendar email'),
        ),
    ]
