# Generated by Django 2.1.5 on 2019-01-27 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_auto_20190127_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=64, verbose_name='Role in project')),
                ('date_joined', models.DateField(verbose_name='Date joined')),
                ('date_left', models.DateField(blank=True, null=True, verbose_name='Date of leaving')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AddField(
            model_name='membershipmodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='membershipmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(through='projects.MembershipModel', to=settings.AUTH_USER_MODEL),
        ),
    ]
