# Generated by Django 2.1.5 on 2019-02-10 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_auto_20190127_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipmodel',
            options={'ordering': ['user'], 'verbose_name_plural': 'Project members'},
        ),
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='project',
            name='estimation_in_man_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='Time estimation in man-hours'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='members', through='projects.MembershipModel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('in progress', 'In progress'), ('completed', 'Completed')], default='started', max_length=32, verbose_name='Status'),
        ),
        migrations.AlterUniqueTogether(
            name='membershipmodel',
            unique_together={('user', 'project', 'role')},
        ),
    ]
