# Generated by Django 2.1.5 on 2019-02-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190210_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='specification',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Specification'),
        ),
        migrations.AlterField(
            model_name='membershipmodel',
            name='role',
            field=models.CharField(choices=[('project manager', 'Project manager'), ('developer', 'Developer'), ('tester', 'Tester'), ('business analyst', 'Business analyst'), ('front-end developer', 'Front-end developer'), ('back-end developer', 'Back-end developer'), ('data scientist', 'Data scientist'), ('designer', 'Designer'), ('team lead', 'Team lead')], default='developer', max_length=64, verbose_name='Role in project'),
        ),
    ]
