# Generated by Django 2.1.5 on 2019-02-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190215_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipmodel',
            name='hours_per_day',
            field=models.IntegerField(default=8, verbose_name='Hours per day'),
        ),
    ]
