# Generated by Django 2.1.5 on 2019-01-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('veryfing', 'Verifying'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='new', max_length=32, verbose_name='Status'),
        ),
    ]
