# Generated by Django 2.1.5 on 2019-01-24 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0002_auto_20190124_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='absence',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
